### PR TITLE
Update documentation.md

### PR DESCRIPTION
**Pull request by inetbiz**
Updates issue #183 with proposed changes. Let people see the code that created the quote.
``` html
> Age is an issue of mind over matter. If you don't mind, it doesn't matter.
<cite>Mark Twain</cite>
<small markdown="1">[Up to table of contents](#toc)</small>
{: .text-right }
```

### CODE REVIEW

**Comment by inetbiz** [comment]
@Phlow I didn't see https://phlow.github.io/feeling-responsive/documentation/ update with the PR?

**Comment by Phlow** [comment]
I got an error. 

The page build failed for the `gh-pages` branch with the following error:

The tag `hightlight` on line 79 in `pages/documentation.md` is not a recognized Liquid tag. For more information, see https://help.github.com/en/articles/page-build-failed-unknown-tag-error.

For information on troubleshooting Jekyll see:

 https://help.github.com/articles/troubleshooting-jekyll-builds

**Comment by inetbiz** [comment]
That's odd? @Phlow same liquid tag found on line 114

**Comment by Phlow** [comment]
Haha, found it – it was a typo of yours

{% hightlight html %}

**Pull request merged**
