### PR TITLE
Update Google Analytics and correct mistyped var

### PR DESCRIPTION
**Pull request by litusgm**
Updated old Google Analytics (analytics.js) to new Global site tag (gtag.js) Google Analytics.

BTW old Google Analytics was not working here because of mistyped variable.

### CODE REVIEW

**Comment by TWiStErRob** [comment]
Where's the mistyped var?

**Comment by litusgm** [comment]
> Where's the mistyped var?

Line 95 of _includes/_head.html file says:
`ga('create', '{{ site.analytics.google.tracking_id }}', 'auto');`
where the variable name should be `site.google_analytics_tracking_id`.

At least for me it wasn't working until I changed this bit of code.

After that I changed the code to use the new gtag.js by Google.

**Comment by TWiStErRob** [comment]
Ah, nice catch, looks like it was copy pasted from the suggestion in #142 about a year ago and didn't sync up with the structure in this config.

**Comment by Phlow** [comment]
Hey @litusgm – Thank you very much!

**Pull request merged**
