### PR TITLE
Prevent title link from dissapearing from subnav for navigation dropdowns on medium screen displays

### PR DESCRIPTION
**Pull request by thegands**

### CODE REVIEW

**Comment by Phlow** [comment]
hey @thegands – Can you explain, what this commit changes? How can I see the current mistake?

**Comment by thegands** [comment]
Sure! To best describe the issue I recorded a little youtube video
https://www.youtube.com/watch?v=Z55XIV14doE. Your template has helped
immensely with my portfolio website so I'm excited to be able to make a
small contribution in return for your amazing work!

**Comment by TWiStErRob** [comment]
That's weird, this was an intentional change in Foundation 5.5.2: https://github.com/zurb/foundation-sites/issues/6393 and the commit: https://github.com/zurb/foundation-sites/commit/5122552427663297d654835798357e53ce1721d2

**Comment by TWiStErRob** [comment]
I remembered this issue, so I double-checked... I made a similar fix: https://github.com/TWiStErRob/twisterrob.github.io/commit/904c48540a2b469fd72611725a89c10d59b45daa#diff-705585893da8551ab2465b9b53760074R2434

The last item dissappearing shouldn't be a concern, because it's unlikely that the device screen will change size while the menu is open.

**Comment by Phlow** [comment]
Thank you for the fix. I pull it in :+1:

**Comment by Phlow** [comment]
By the way, the youtube video was a great idea to illustrate it :)

I am curious: What's the URL of your site?

**Comment by thegands** [comment]
Thanks @TWiStErRob ! The fact that it was an intentional change in Foundation is very strange, I may have to investigate further...

and thanks for committing my pull request @Phlow :smiley:

my website is located at http://thegands.github.io and I will have an article about this pull request posted in my blog shortly! :stuck_out_tongue:

**Comment by Phlow** [comment]
I like the idea of how you put that logo into the header :)

**Pull request merged**
