### PR TITLE
Corrected logo.png location

### PR DESCRIPTION
**Pull request by funkypenguin**
Corrected image location for logo.png

### CODE REVIEW

**Comment by Phlow** [comment]
There are lots of funky penguins in your code ;)

Where did you correct the logo.png location? Maybe I do it mysef.

**Comment by funkypenguin** [comment]
Oops. I'm a github newbie. I meant to only pull-request this change:
https://github.com/funkypenguin/funkypenguin.github.io/commit/ee052be59f549f6a12adf6794ba73fe419e8a65a

:smile: 
D

**Comment by Phlow** [comment]
I am a newbie, too. But I am very glad, you squeezed these little errors and told me. I will update this tomorrow.

**Comment by Phlow** [comment]
It's done.

**Pull request closed without merging**
