### PR TITLE
Let's See

### PR DESCRIPTION
**Pull request by tmoss4**

### CODE REVIEW

**Comment by Phlow** [comment]
I think you did something wrong. 😜

**Comment by tmoss4** [comment]
I did >< I'm still learning, just ignore me

**Comment by Phlow** [comment]
No problem… In the beginning it was all (and sometimes is) confusing to me…

**Comment by tmoss4** [comment]
I'm sure I'll get better if I keep on it :3

Forking the repo and changing your name to mine broke a couple things on my page but I found an interesting solution that I'd like your opinion on:
1. I removed the "/feeling-responsive" repo name in the config.yml file so that it's just "url: 'https://tmoss4.github.io'"
2. I changed a line in _frontpage-widget.html and removed "{{ site.baseurl }}" where it appeared after "{{ site.urlimg }"
3. I added a "{{ site.baseurl }}" to both headers.md and design.md
These fixes seem to fix all the issues that I was having but I'm not sure if any of this was in bad practice.

It was really interesting to me that you had baseurl blank but that seems to be standard as many tutorials said that it should be filled after you fork a theme. That begged the question for me why your site is able to work without it and why you call baseurl in your existing code. It was equally interesting when removing the /reponame fixed things as it appears GitHub pages is setting it automatically perhaps? 

I'm not sure if I experienced some issues because I forked the theme rather than downloading/uploading onto a repo myself. I'd love to see a guide or video about using the theme from that very first step since it's where I had all my trouble!

I'm also doing my best to learn more about url, siteurl, and baseurl. Your theme is amazing by the way!

**Comment by TWiStErRob** [comment]
@tmoss4 You shouldn't need to modify those files, only the config. However those (2 and 3) might as well be bugs.

Read this: https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/

[Regarding GH-pages, there are two ways to host](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/):
- `master` branch in `github.com/user/user.github.io` is on `user.github.io`  
  in this case `baseurl: ''`
- `gh-pages` branch in `github.com/user/repo` is on `user.github.io/repo`  
  in this case `baseurl: '/repo'`

@Phlow uses the second one, but when you fork you should rename the repo to `user.github.io` and change the branch to `master`; that way you can host on a domain.

---

As an example here my site copied (not forked) from an older version of this repo, hosted as the main repo for my username:
https://github.com/TWiStErRob/twisterrob.github.io
particularly the configs related to baseurl:
https://github.com/TWiStErRob/twisterrob.github.io/blob/master/_config_dev.yml#L7-L11
https://github.com/TWiStErRob/twisterrob.github.io/blob/master/_config.yml#L31-L44
**Note that this may be [in conflict with how Phlow uses them](https://github.com/Phlow/feeling-responsive/issues/47#issuecomment-133053617), because I want everything to be as relative as possible.** Choose an approach and stick to it, don't mix and match.

**Comment by tmoss4** [comment]
@TWiStErRob Thanks for the response. 

Your site makes perfect sense to me as it is setup as a user page and so doesn't require a baseurl. My site (and the original theme) is setup as a project page but I've still gotten it to work without using a baseurl or including the repo name in the config url. I find this particularly strange but tested it with other themes where it also worked. Can you explain this behavior? Which files are you saying I didn't need to modify because I tried various arrangements of the url and baseurl that didn't resolve the issues fixed by solutions 2 and 3.

The last link you added about how Phlow uses urls was interesting because I did have the entire site working in my local environment but breaking in production and I think jbiatek's comment explained why. 

Parker's article is great and I've read it many times before this!

my site: https://tmoss4.github.io/feeling-responsive/
config: https://github.com/tmoss4/feeling-responsive/blob/gh-pages/_config.yml

**Comment by TWiStErRob** [comment]
@tmoss4 I think your site only works on the surface. Try to click the links in the footer, or the blog posts on the home page below "More articles", they all go to 404 due to your config changes.

Regarding 2) and 3) they may be actual bugs, @Phlow needs to look into. They may be in branches of code that usually don't execute unless config is modified.

**Comment by tmoss4** [comment]
You're quite right! That was the same problem I was having with the links that required solution 3. I think there may be another place in the code that needs a site.url or site.baseurl. If I find it successfully I'll let you know. Thanks for your help :3

**Comment by TWiStErRob** [comment]
Why don't you just use the same config as Phlow if your hosting situation is the same? (i.e. normal repo, not a user.GH.io)

**Comment by tmoss4** [comment]
That was the very first thing I tried, however, the page did not load correctly for reasons I am still exploring. I'm not sure if it was something I did incorrectly. Try forking the theme as it is now and using the same config as Phlow and let me know if it works.

**Comment by TWiStErRob** [comment]
I can't do it right now, it looks like CNAME changes behavior. I contacted support to clear it up.

**Comment by tmoss4** [comment]
No worries. In the mean time I've found one of the areas where some "{{ site.baseurl }}" snippets could be added in lists-posts which is in the includes folder. That program houses the logic that surfaces the blog posts on the home page below "More articles" so that is also fixed now.

**Comment by tmoss4** [comment]
And now I've fixed the links in the footer. The solution I used was... you guseed it, adding "{{ site.baseurl }}" snippets to some spots in footer.html. For some reason "assign domain = site.url + site.baseurl" was not actually adding the site.baseurl (perhaps understandably so because it's not technically set in my config.yml) so I added it manually to the areas where links were breaking. 

The theme is so lovely that I don't want to criticize but additional commenting or some kind of guiding document would be SO helpful. The logic is intricate and can get rather involved. At least, that's how I, some guy with little experience, feel. Maybe it's only moderately invovled but it's certainly got more moving pieces than most of the other themes I've seen.

**Comment by Phlow** [comment]
There was a[ significant change for GitHub Pages](https://github.com/blog/2277-what-s-new-in-github-pages-with-jekyll-3-3).

They changed the handling of baseurl. It gets now set **automatically** and uses the name of your repo. I adjusted the theme…

I prefer absolute URLs – They are more convenient to me and you have less code, and it's not so confusing. So if you want to use _Feeling Responsive_ with GitHub Pages, you have to configure it like this:

```
url: 'https://phlow.github.io'
baseurl: '/feeling-responsive'
```

In your case @tmoss4 

```
url: 'https://tmoss4.github.io/'
baseurl: ''
```

Hope that help…

**Comment by TWiStErRob** [comment]
@Phlow I don't get it, both your and his repo has the same name, branch, only under a different user. Why do you need different configuration for these two seemingly equivalent scenarios?

**Comment by Phlow** [comment]
I haven't read the whole thread to be honest. I just figured out, that I didn't do it right.

I think, this week, I will use the new 

[relative_url and absolute_url filters](https://jekyllrb.com/news/2016/10/06/jekyll-3-3-is-here/)

And I will ty to get rid of this {{ site.url }}{{ site.baseurl }} solution.

**Pull request closed without merging**
