### PR TITLE
Add Yandex SEO tools META

### PR DESCRIPTION
**Pull request by ghost**
Adds [Yandex Webmaster tools](https://webmaster.yandex.com/) support as [ported from `habd.as`](https://github.com/jhabdas/habd.as/search?utf8=%E2%9C%93&q=yandex). Removes Alexa as cruft.

screen shot 2016-12-01 at 7 34 19 pm

### CODE REVIEW

**Comment by jhabdas** [comment]
Nice theme.

screen shot 2016-12-01 at 6 36 59 pm

**Comment by TWiStErRob** [comment]
Why not leave both? Users would fill in whichever ID they have in config and then "it just works". IMO nothing should be forced, especially since it's easy to implement.

**Comment by ghost** [comment]
Users can no longer sign up for Alexa accounts as of a few months ago.

**Comment by TWiStErRob** [comment]
Hmm, ok. What about existing users?

**Comment by ghost** [comment]
Let me triple check the Alexa stuff. Last I checked was a couple of months ago, I was using a theme and lost time after finding out Alexa wasn't allowing new users. Current users should have their own migration strategy IMO.

**Comment by ghost** [comment]
Never mind. Robert, I see your point. Updating with feedback

**Comment by ghost** [comment]
Updated. Ready for review.

**Comment by ghost** [comment]
Food for thought. Cannot speak to the authoritativeness, only that it helps substantiate my suggestion to remove Alexa. YMMV http://www.johnfdoherty.com/meta-descriptions-that-will-not-help-seo/

**Comment by TWiStErRob** [comment]
That seems to reference "alexa" meta, while this is an Alexa verification ID, they do different things in my reading, one is an imaginary hack to increase ranking, the other is a verification tool for webmasters to prove they own the site. *Edit: too late to ignore* ;)

**Comment by ghost** [comment]
At second glance ignore that last post.  It looks irrelevant. Sorry, Just woke up. :)~

**Comment by ghost** [comment]
@Phlow Would you mind giving Robi  contributor access to this repo?  I've got time for some PR's

**Comment by TWiStErRob** [comment]
That's not necessary, he's the owner. I don't want to take over, he should be deciding about scope (i.e. what to merge and implement). I'll just keep giving my 2 cents ;)

**Comment by Phlow** [comment]
Thankyou. I added it.

**Pull request merged**
