### PR TITLE
Provide typography setting to control hyphenation in the body paragraphs

### PR DESCRIPTION
**Pull request by wbreeze**
Introduced a variable in settings that enables change to the hyphenation behavior in paragraphs of the body.

### CODE REVIEW

**Comment by Phlow** [comment]
I am sure, it's helpful for you. But this change makes it more complicated. I want to keep it like it was.

**Comment by wbreeze** [comment]
You just caused me to fork, because I need this feature.  The hyphenation is horrible.

It was a very simple variable subsitution, how more complicated?

It doesn't add any additional jekyll exposed options, so is transparent at that level.

In order to use it, one has to copy-out the settings file and change the value of the variable, i.e. read the code.  That makes it, in my view, a power user feature.

But do as you like. I'm just making the case.

**Comment by Phlow** [comment]
OK, I make you happy.

**Comment by wbreeze** [comment]
Wow! Thank you for allowing me to make a case. Thank you for taking these little changes.  I love this theme.  It's great!  I used the foundation grid features in the form that I built.  Really works out nicely.

**Comment by Phlow** [comment]
You're welcome.

**Pull request merged**
