### PR TITLE
Handling external links gracefully

### PR DESCRIPTION
**Pull request by michiexile**
You are setting `_baseurl` but then using `site.baseurl`.

### CODE REVIEW

**Comment by TWiStErRob** [comment]
Nice one!

**Comment by Phlow** [comment]
@michiexile Sorry for my late response. I don't understand

    {{ _baseurl }}

Is it a new command in Jekyll?

What does it do?

**Comment by TWiStErRob** [comment]
It's a local variable defined a few lines above that takes URL prefix into account.

**Comment by Phlow** [comment]
@TWiStErRob @michiexile Now I get it ;) – Took a while.

**Pull request merged**
