### PR TITLE
sayid

### PR DESCRIPTION
**Pull request by sayidso**

### CODE REVIEW

**Comment by ghost** [comment]
o_() big pull

**Comment by Phlow** [comment]
I don't understand the pull request. No information.

**Comment by ghost** [comment]
@Phlow I believe this pull was a misfire. Michael Rose told me he seems them on his FOS repos.

**Comment by Phlow** [comment]
That was my feeling, too. That's why I closed it.

**Comment by ghost** [comment]
$10 and a brewski says they're coming from https://github.com/github/hub

**Comment by jhabdas** [comment]
Hey, while I've got your attention. Informal feature request! https://github.com/jekyll/jekyll-feed/issues/124

**Comment by jhabdas** [comment]
To be sure, I'm requesting collection feeds, not the feed gem.

**Comment by Phlow** [comment]
Hey Josh. Currently I am downsizing a lot of my activities. And I haven't done anything new to *Feeling Responsive* in quite a while. I am thinking about giving someone else *Feeling Responsive*. If I manage to let it go, are you interested to get the ownership of feeling responsive?

**Comment by Phlow** [comment]
One more note: Do you really live in Bali? I read a lot about the people over there.

**Comment by jhabdas** [comment]
Shit. I totally forgot to update my location... Just kidding. I'm still here. Bali bebas!

**Comment by Phlow** [comment]
Is it nice?

**Comment by jhabdas** [comment]
jhabdas@gmail.com me

**Pull request closed without merging**
